<?php
//debug($_SESSION, "session");
//debug($_SERVER, "server");
//$_SESSION=[];
?>

	<p style="margin-left:50%; margin-right:50%" class="btn btn-warning"><a style="white-space:nowrap;" class="btn" href="https://www.cowboysfringants.com/biographie/">sources : site officiel des Cowboys Fringants</a></p>
<br>
<style>
    .titre{
        text-align:center;
        margin:25px;
    }
    .citation{
        text-align:right;
    }
    .auteur{
        text-decoration:underline;
    }
</style>
<div style="margin-left:15%;margin-right:15%;">
    <div class="titre">
        <h1>Des débuts modestes</h1>
    </div>
    Karl Tremblay et Jean-François Pauzé se rencontrent pour la première fois en septembre 1994 dans un vestiaire de hockey.<br>Ils venaient de terminer le camp d’entraînement et étaient maintenant officiellement membres des Jets de Repentigny, un obscur club junior B. Fruit du hasard ou du destin, cette rencontre sera déterminante pour le restant de leurs jours.De natures timides, les deux jeunes hommes ne s’adresseront la parole qu’au mois de janvier 1995.<br>Mis au courant que Jean-François grattait la guitare, Karl lui affirme qu’il est chanteur et qu’il se cherche des musiciens pour former un groupe. C’est sans grand enthousiasme que Pauzé l’invitera à jammer dans le sous-sol de ses parents en février 1995.<br>Grâce à l’insistance de Tremblay, ils composeront ce soir-là leur première chanson intitulée Les routes du bonheur et une deuxième, Gaétane, suivra le lendemain soir. C’était le début de l’ère des chansons de peines d’amour mal enregistrées où les noms de villes et les marques de voitures se succédaient.<br>À cette époque, ils composeront ensemble une vingtaine de chansons dont 12 se retrouveront ultérieurement sur l’album cassette 12 Grandes Chansons. Nous y reviendrons.<br>
    <div class="titre">
       <h3>L’été 1996 </h3>
    </div>
    À peu près à la même époque, Jean-François rencontre Marie-Annick Lépine alors qu’ils occupent le même emploi d’été.<br>Étudiante et violoniste, Lépine semble plus s’intéresser au côté rebelle de Pauzé qu’à son talent de musicien.<br>Issue du milieu de la musique classique, elle n’a rien à foutre des ridicules chansonnettes country que composent Karl et J-F.<br>Cependant, elle changera son fusil d’épaule lors d’un certain concours de musique amateur. Très amateur faut-il spécifier.<br>
    <br>
    Nous sommes à l’été 1996. Karl et J-F décident de tenter leur chance au concours d’auteurs-compositeurs de la brasserie La Ripaille de Repentigny.<br>Après une audition plus ou moins formelle avec un organisateur conquis par leurs chansons rigolotes, les deux larrons s’attaquent donc au concours où ils termineront finalement en 2ème place derrière Garnote, un groupe néo-hard-rock-progressif.<br>L’élément déclencheur venait de se produire : des foules nombreuses vinrent les encourager si bien que le soir de la finale, on dut refuser du monde à la porte. Conquise par les réactions suscitées par les gens, Marie-Annick accepta même de se joindre au duo pour les demi-finales et la finale.<br>Le troisième morceau du puzzle se mettait en place.<br>
    <br>
    Forts de ce nouvel engouement local, le nouveau trio se mit à la recherche d’un bassiste et d’un batteur.<br>Ils jetèrent leur dévolu sur un jeune néophyte de la basse âgé de seize ans en Jérôme Dupras. Petit cousin de Marie-Annick, le grassouillet adolescent sera celui qui dénichera plus tard un batteur à la formation en Domlebo.<br>Ce dernier, alors percussionniste de la formation Windstorm semble enjoué par le caractère loufoque de la bande et décide de rester pour l’été seulement, le temps d’enregistrer la première cassette. Après, disait-il, il devait se concentrer sur ses études. On connaît tous la suite.<br>
    <div class="titre">
        <h3>1997</h3>
    </div>
    Si 1997 saluait l’arrivée dans le groupe de Domlebo et de Jérôme Dupras, cette année marquait aussi la sortie anonyme de leur premier album : 12 Grandes Chansons. Imprimée à cinq cent exemplaires, la cassette originale s’écoulera en quelques mois à des amis et à des connaissances.Quelques spectacles aussi mythiques que loufoques parsemèrent l’été et l’automne 1997, tous dans leur région natale de Lanaudière (La Ripaille, L’Oasis du vieux Palais, le bar du Portage).<br>
    <div class="titre">
        <h3>1998</h3>
    </div>
    À l’hiver 1998, J-F Pauzé abandonne ses études momentanément pour se consacrer au groupe avec Domlebo qui remet aussi en question sa carrière dans le domaine de la santé.<br>Pauzé et Lebeau se mettront alors à la composition du prochain album qui sera enregistré en 2 jours à l’automne 1998.<br>L’album Sur mon Canapé sort en petites pompes au mois de novembre 1998.<br>Les Cowboys Fringants sortent ainsi un deuxième disque autoproduit et auto-distribué en l’espace d’un an.<br>Cet autre objet rare se vendra à plus de mille exemplaires grâce au bouche à oreille tant et si bien que l’album commence à faire fureur dans les radios étudiantes et lors des partys de cégep partout au Québec.<br>Un pas de plus vient d’être franchi par la joyeuse bande qui ne demande pas mieux que de jouer partout. Le groupe se produira même à Montréal dans un Petit Campus bondé à la fin de 1998 lors d’un spectacle mythique qui confèrera aux Cowboys le titre de groupe de party.<br>
    <div class="titre">
        <h1>1999-2000</h1>
    </div>
    1999 représente une année charnière pour le groupe puisqu’il effectuera sa véritable percée montréalaise.<br>Présents lors de nombreux Cabarets Kerozen et en demande sur les ondes de CISM et CIBL, les Cowboys tâtent le terrain auprès des compagnies de disque de la métropole.<br>Leurs démarches seront toutefois restées vaines.<br>Ils se verront même refuser l’accès des bureaux de la plupart des entreprises.<br>Leur 2ème place au concours des Francouvertes ne les aidera en rien à signer une entente.<br>Ils n’ont alors guère le choix que de retourner vers l’autoproduction pour la sortie leur nouvel album, Motel Capri,  en avril 2000. Nouveauté pour le groupe, l’album est toutefois mis en licence par l’Empire Kerozen et aura droit à une distribution en magasins.<br>
    <br>
    Motel Capri représente la véritable éclosion.<br>Bien qu’encore embryonnaire, le succès du groupe ne se dément plus.<br>Encore charrié par le bouche à oreille (les radios commerciales refusent toujours de les faire tourner), le groupe jouit maintenant d’un véritable bassin de fidèles qui les suit partout au Québec.<br>Annonciateur de ce qui allait se produire dans l’avenir, leur spectacle lors des Francofolies de Montréal de l’été 2000 en fut un d’anthologie. Une marrée humaine s’agglutinera aux abords de la trop petite scène Radio-Canada pour danser et chanter en communion avec ce nouveau groupe de la relève.<br>La cinquantaine de spectacles qu’ils donneront au cours de la tournée Motel Capri leur fera gagner un plus vaste public, conquis par leurs performances scéniques aussi énergiques que débraillées.<br>
    <div class="titre">
        <h1>Période 2002-2019</h1>
    </div>
    À l’hiver 2001, Pauzé se mettra à l’écriture de ce qui deviendra l’album phare de la formation.<br>Si Motel Capri représentait l’éclosion du groupe, Break Syndical (mars 2002) le fera exploser.<br>Cette fois-ci, c’est la bonne! Avec des critiques dithyrambiques en poche, la bande part en tournée dès le mois de mars.<br>La vague  des Cowboys Fringants et de leurs fans aux chandails verts déferlera sur le Québec en entier en 2002 et 2003.<br>Véritable phénomène, la formation se produit à guichets fermés partout au Québec devant des fans conquis d’avance à leurs chansons tantôt drôles, revendicatrices ou nostalgiques.<br>Au cours de cette tournée, le public découvre en Karl Tremblay un véritable meneur de foules et en Marie-Annick  Lépine une multi instrumentiste accomplie qui confirme les Cowboys comme groupe de spectacle par excellence.<br>Par ailleurs, les radios commerciales, qui boudaient jadis le groupe, n’ont guère le choix d’entrer dans la danse puisque les fans réclament littéralement que leurs chansons tournent sur leurs ondes.<br>La chanson Toune d’automne deviendra un des grands succès de 2002 ce qui ne nuira pas aux ventes de Break Syndical.<br>
    <br>
    L’été 2002 se terminera par un tour de force, soit le spectacle au Parc Jarry avec Plume Latraverse devant 8000 personnes.<br>Puis la série de spectacles se continuera au cours de l’automne jusqu’à son paroxysme : la tournée montréalaise de décembre 2002.<br>Idée saugrenue s’il en était une, cette tournée audacieuse visait à refaire le parcours de toutes les salles montréalaises où s’était produit le groupe depuis ses débuts.<br>Des Verres stérilisés  jusqu’au Métropolis en passant par le Petit Campus, le Cabaret et le Spectrum, le groupe roulera à un train d’enfer lors de ce mois où les dix spectacles montréalais s’ajoutaient à d’autres en province.<br>
    <br>
    2003 verra la Tournée Break Syndical s’accentuer. Au mois de mai, le groupe sort son premier album live Attache ta tuque! qui inclut des versions des spectacles de la tournée montréalaise.<br>Après un été bien rempli au niveau des festivals c’est le dernier droit de la tournée et à l’automne, le groupe rafle les Félix de l’album alternatif, du groupe de l’année et du spectacle de l’année au gala de l’Adisq.<br>Pour conclure la longue tournée, les Cowboys essoufflés s’offrent le Centre Bell pour la première fois de leur carrière.<br>Le pari est risqué : remplir les 20 000 sièges disponibles, ce que peu d’artistes québécois ont osé faire par le passé.<br>Malgré les inquiétudes à l’aube du 30 décembre, les Cowboys et leurs fans pourront dire mission accomplie au terme d’une soirée mémorable dont les images et le son ont été gravés sur DVD (Les Cowboys Fringants, Centre Bell – 30 décembre 2003.) Ainsi se complétait la Tournée Break Syndical au terme de 153 concerts.<br>Puis en avril 2004 la France entrouvre ses portes au groupe qui fait salle comble à l’Élysée Montmartre de Paris lors d’un spectacle aussi exceptionnel que déroutant à l’écoute de ces Français qui chantaient à tue-tête ces chansons écrites en québécois.<br>C’est le début d’une belle histoire en Europe francophone où ils jouissent désormais d’un étonnant bassin de fans.<br>
    <br>
    Battre le fer pendant qu’il est chaud, telle était la devise des Cowboys qui se retrouvent en studio dès le mois de mai suivant pour préparer la sortie de leur prochain album La Grand-Messe (novembre 2004.)<br> Entre temps, les Cowboys sont primés groupe de l’année pour une deuxième fois de suite au Gala de l’Adisq d’octobre.<br>La Grand-Messe, la nouvelle mouture tant attendue est sur les tablettes le 23 novembre. Cette nouvelle parution engendre bien sûr la tournée du même nom qui s’amorcera quatre jours après la sortie du disque à St-Jean-sur-le-Richelieu. Puis le début de l’année 2005 sera marqué par la série de 16 spectacles à La Tulipe à Montréal, tous à guichets fermés.<br>L’été s’amorcera sous le signe de la controverse avec la St-Jean-Baptiste sur l’île Notre-Dame.<br>Cette initiative du groupe qui voulait un spectacle plus politisé avec des artistes comme Loco Locass, les Zapartistes et Mononc’ Serge s’avérera un véritable succès malgré la polémique engendrée par les médias au sujet du caractère payant de l’événement.<br>Toutefois, 25 000 personnes heureuses et consentantes déferleront sur le circuit Gilles-Villeneuve  au cours de cette suffocante journée du mois de juin.<br>
    <br>
    À l’automne 2005, le groupe remportera le Félix de la chanson de l’année avec Les Étoiles Filantes et poursuivra sa tournée au Québec et en France.<br>Parallèlement, Jérôme Dupras et ses comparses mettent sur pied la Fondation Cowboys Fringants qui se concentre sur des projets de conservation de la nature et de sauvegarde des écosystèmes menacés en territoire québécois.<br>Puis, comme en 2003, la tournée de la Grand-Messe se terminera de merveilleuse façon au Centre Bell, le 30 décembre 2006.<br>Au terme des 186 spectacles de cette tournée de la Grand-Messe qui les aura amenés aux quatre coins du Québec, des Maritimes et de l’Europe francophone, les Cowboys Fringants s’accordent un petit congé bien mérité avant de repartir sur la route. La Grand-Messe, un album qui n’aura laissé personne indifférent, aura finalement vendu plus de 230 000 copies en deux ans.<br>
    <br>
    À l’été 2007, le groupe qui était en pause depuis le début de l’année repart sur la route pour une tournée surprise de festivals.<br>Celle-ci se termine sur une triste note puisqu’au lendemain de la dernière prestation qui avait lieu au Festival International des Montgolfières de St-Jean-sur-le Richelieu, le batteur Dominique Lebeau annonce qu’il quitte les Cowboys Fringants après une association de 10 ans.<br>Ébranlés par cette nouvelle aussi surprenante qu’imprévisible, les membres de la formation n’ont guère le choix que de se serrer les coudes et d’unir leurs efforts pour maintenir le groupe en vie.<br>
    <br>
    C’est donc en tant que quatuor que les Cowboys s’attaquent à l’écriture et à la réalisation de leur prochain opus.<br>La fin de 2007 s’avérera une période fort créative pour J-F Pauzé qui écrira pas moins de trente chansons en moins de six mois.<br>Fruit de l’expérience acquise avec les Cowboys ainsi qu’avec son album solo «Au bout du rang» et de nombreuses collaborations, la multi-instrumentiste Marie-Annick Lépine texturera méticuleusement les nouvelles chansons d’arrangements fort à propos et tout en nuance. Jérôme Dupras fera office de batteur-bassiste pour l’élaboration des maquettes et enregistrera même quelques pistes officielles à la batterie sur l’album en chantier.<br>Le reste de la tâche percusive sera assurée par le batteur d’expérience Steve Gagné.<br>Les Cowboys décident également de changer de collaborateurs en studio et s’associeront à Louis Legault (Daniel Bélanger, Dumas) pour l’enregistrement et la réalisation de l’album.<br>
    <br>
    Devant la trentaine de chansons qu’ils ont devant eux, l’idée d’un possible album double est évoquée mais est finalement écartée en raisons de complexité au niveau marketing et de la production.<br>C’est alors que germe la possibilité de sortir deux albums distincts : l’un plus texturé et l’autre plus broche à foin.<br>Ainsi naîteront L’Expédition (23 septembre 2008) et Sur un air de déjà vu (17 février 2009), deux disques salués par les fans du groupe et la critique.<br> L’album principal qu’est L’Expédition se veut plus posé, nuancé et poétique que ce que les Cowboys Fringants nous avaient habitué auparavant.<br>Les textes à la fois évocateurs et porteurs d’espoir y sont livrés avec une sensibilité parfaitement dosée par la voix chaleureuse du chanteur Karl Tremblay, plus que jamais en contrôle de ses moyens.<br>Les trois premiers extraits de l’album (Entre deux taxis, Tant qu’on aura de l’amour et La tête haute) se hisseront au sommet des palmarès radiophoniques québécois.<br>Du jamais vu en moins de 6 mois.<br>
    <br>
    Sur un air de déjà vu est quant à lui un album plus guilleret, rappelant le côté bon enfant des débuts des Cowboys.<br>Présenté plus ou moins comme un album de «b-sides», SUADDV réconfortera les partisans du groupe qui déploraient l’absence du côté humoristique sur L’Expédition.<br>
    <br>
    Avec deux nouveaux opus sous le bras, les Cowboys reprennent la route. La tournée de L’Expédition se met en branle à Brossard le 6 novembre 2008 et mènera le groupe aux quatre coins de la Belle Province et de l’Europe.<br>Soucieux de passer de la parole aux actes, le groupe fera de L’Expédition sa «tournée verte» puisque le Co2 émis par les véhicules du groupe et des gens qui assisteront aux spectacles sera annulé par la plantation de 35 000 arbres.<br>Sur scène, exit les cuivres et place à un multi-instrumentiste de talent du nom de Daniel Lacoste (guitares, piano, mandoline, accordéon) pour appuyer Marie-Annick.<br>Le rôle de batteur est maintenant assuré avec brio par Marc-André Brazeau (Band de Garage).<br>
    <br>
    En février 2009, les Cowboys Fringants foulèrent les planches du mythique Olympia de Paris l’instant de trois spectacles mémorables à guichets fermés devant des publics survoltés.<br>Puis suivirent coup sur coup deux salles de 6000 personnes à la Halle Tony-Garnier de Lyon et à l’Aréna de Genève qui conclurent cette surréaliste tournée éclair de dix jours en sol européen où 20 000 spectateurs ont pu voir les Cowboys Fringants en cinq spectacles.<br>
    <br>
    Retour en sol européen en avril 2009 (Toulouse, Caen, Lille, Le Mans et 2 soirs à Bruxelles) et en novembre 2009 où c’est la tournée des Zénith !<br>Les Cowboys se produisent dans les plus grandes salles en province… Strasbourg, Lyon, Reims, Nantes en passant par le Zénith de Paris (8000 personnes qui font littéralement exploser le décibelomètre !) et un autre aréna de Genève plein.<br>Juste en 2009, c’est 40 000 fans européens qui auront vu les Cowboys !<br>
    <br>
    Le 31 décembre 2009, le groupe  s’exécute à Montréal au Centre Bell pour la troisième fois de son histoire.<br>Au printemps, ils retournent en France et en Belgique, avec un passage au Printemps de Bourges devant une foule de 9000 personnes : c’est la première fois dans l’histoire du festival qu’un artiste québécois est en tête d’affiche du Phénix, la salle principale.<br>Ce voyage est accompagné par la sortie d’un album live enregistré au Zénith de Paris en novembre 2009.<br>Juillet 2010, le groupe donne un concert magique aux Francofolies de La Rochelle.<br>
    <br>
    En juillet 2011, 80 000 personnes se massent devant la scène du Paléo Festival de Nyon en Suisse lors d’un concert mémorable lors duquel le groupe fut déclaré « Coup de cœur » par les festivaliers.<br>
    <br>
    La Tournée de L’Expédition s’est terminée en septembre 2011, au terme de plus de 200 concerts au Québec et dans la francophonie.<br>Entre temps, les Cowboys peaufinèrent les chansons de leur huitième album studio (Que du Vent, novembre 2011).<br>
    <br>
    À l’automne 2011, la tournée Que du vent prend son envol.<br>Le groupe donnera près de 300 spectacles dans la francophonie échelonnés sur une période de trois ans.<br>En mai 2014, avec le concours de sa fondation, le groupe met sur pied le spectacle « Un arbre pour tous ».<br>Pour l’occasion, 12 000 personnes se rassembleront au Centre Bell afin d’entendre Patrick Groulx, Louis-José Houde, Les Trois Accords et Les Cowboys.<br>Au terme de cette soirée mémorable, 40 000 arbres seront plantés.<br>« Ce soir vous avez planté une forêt », dira Karl Tremblay au public conquis.<br>Le dernier concert de la tournée Que du vent eut lieu le 20 septembre 2014 à Toronto.<br>
    <br>
    Dès leur retour au Québec, les membres de la formation entrent période de création afin de peaufiner ce qui deviendra l’album Octobre.<br>Nouvelle approche pour le groupe qui s’adjoint les services de réalisateurs chevronnés, Gus Van Go et Werner F.<br>Enregistré entre avril et septembre 2015, Octobre sort le 23 octobre suivant.<br>Aussitôt, les Cowboys repartent en tournée et l’effet dynamo des chansons Bye Bye Lou, Octobre, Pizza Galaxie, La Cave et surtout Marine Marchande les propulse vers de nouveaux sommets.<br>Un public renouvelé de jeunes et moins jeunes se réunit pour chanter les hymnes du groupe.<br>
    <br>
    Avec des foules record dans plusieurs festivals, une tournée à guichets fermés au Québec et l’album rock de l’année au gala de l’ADISQ, la troupe s’envole pour l’Europe en vue d’une série de concerts plus grande que nature qui culminera le 8 avril 2017 au Halle Tony-Garnier de Lyon devant 9000 spectateurs.<br>
    <br>
    En février 2017, le groupe se voit remettre le prestigieux prix Rideau par les diffuseurs de spectacles du Québec.<br>En septembre 2018, le public des Cowboys Fringants est convié à la Maison Symphonique pour quatre concerts mythiques avec l’Orchestre Symphonique de Montréal sous la direction du Maestro Simon Leclerc.<br>
    <div class="citation">
    « Ce fut chaud. Très chaud. Fort. Très fort.<br>Ici, personne à genoux pendant les hymnes : une foule debout, trépidant à l’unisson sur En berne ou La manifestation.<br>Le public s’est payé un « party » géant à la Maison symphonique dans une ambiance électrique. »<br><span class="auteur">– Christophe Huss, Le Devoir</span> 
    </div>
    Devant le succès de la série de concerts, plusieurs dates ont été ajoutées à Montréal et au Grand Théâtre de Québec (avec l’OSQ).
    <br>
    À l’été 2019, c’est au tour du Cirque du Soleil de s’associer aux Cowboys Fringants via un spectacle-hommage qui tient l’affiche pendant un mois à l’Amphithéâtre Cogeco de Trois-Rivières.<br>Du 17 juillet au 17 août, les fans de toutes les régions du Québec (et de la francophonie !) convergent à Trois-Rivières pour assister au spectacle Joyeux Calvaire.<br>Au terme de la série couronnée par un record absolu d’affluence en cinq ans d’association avec le Cirque, l’Amphithéâtre Cogeco offre au groupe de terminer sa tournée sur ses planches.<br>L’aventure Octobre prend donc fin officiellement le 20 septembre 2019, près de quatre ans après la sortie du disque.<br>
    <br>
    Le 4 octobre 2019 est officiellement lancé l’album Les Antipodes.<br>Le dixième album de la formation reçoit un accueil fort enthousiaste.<br> L’engouement pour le groupe est toujours aussi fervent et la tournée affiche déjà complet avant même son premier concert.<br>Vingt-cinq ans après leur formation, les Cowboys demeurent toujours aussi actuels, rassembleurs et fédérateurs.<br>
    <br>
    <div class="citation">
    « C’est somptueux, c’est festif, c’est ambitieux, mais aussi délicieusement triste. Du grand Cowboys!<br>D’accord, consacrer Les Antipodes comme le zénith du projet serait un exercice cruel.<br> Entendons-nous qu’il figure au moins parmi les meilleurs du quatuor ! »<br><span class="auteur">- André Péloquin, Le Journal de Montréal</span>
    </div>
    À ce jour, les Cowboys Fringants ont vendu plus de 1 300 000 albums dans la Francophonie, planté presqu’autant d’arbres et leurs chansons ont été – et sont encore – le «décor» et la toile de fond de la vie de milliers de personnes.
    <br>
</div>

